# Generated by Django 3.0.3 on 2020-08-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('characteristic', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='intstore/', verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опублековано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='intstore.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-published'],
            },
        ),
    ]
